version: '3.8'

services:
  ambev.developerevaluation.webapi:
    environment:
      - ConnectionStrings__DefaultConnection=Host=ambev.developerevaluation.database;Port=5432;Database=developer_evaluation;Username=developer;Password=ev@luAt10n;Pooling=true;